// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "eticketing/module/entities"

	mock "github.com/stretchr/testify/mock"
)

// ScheduleRepositoryInterface is an autogenerated mock type for the ScheduleRepositoryInterface type
type ScheduleRepositoryInterface struct {
	mock.Mock
}

// CreateSchedule provides a mock function with given fields: schedule
func (_m *ScheduleRepositoryInterface) CreateSchedule(schedule *entities.ScheduleModels) (*entities.ScheduleModels, error) {
	ret := _m.Called(schedule)

	var r0 *entities.ScheduleModels
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.ScheduleModels) (*entities.ScheduleModels, error)); ok {
		return rf(schedule)
	}
	if rf, ok := ret.Get(0).(func(*entities.ScheduleModels) *entities.ScheduleModels); ok {
		r0 = rf(schedule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ScheduleModels)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.ScheduleModels) error); ok {
		r1 = rf(schedule)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSchedule provides a mock function with given fields: scheduleID
func (_m *ScheduleRepositoryInterface) DeleteSchedule(scheduleID uint64) error {
	ret := _m.Called(scheduleID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(scheduleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaginatedSchedules provides a mock function with given fields: page, pageSize
func (_m *ScheduleRepositoryInterface) GetPaginatedSchedules(page int, pageSize int) ([]*entities.ScheduleModels, error) {
	ret := _m.Called(page, pageSize)

	var r0 []*entities.ScheduleModels
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]*entities.ScheduleModels, error)); ok {
		return rf(page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(int, int) []*entities.ScheduleModels); ok {
		r0 = rf(page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.ScheduleModels)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetScheduleByID provides a mock function with given fields: scheduleID
func (_m *ScheduleRepositoryInterface) GetScheduleByID(scheduleID uint64) (*entities.ScheduleModels, error) {
	ret := _m.Called(scheduleID)

	var r0 *entities.ScheduleModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*entities.ScheduleModels, error)); ok {
		return rf(scheduleID)
	}
	if rf, ok := ret.Get(0).(func(uint64) *entities.ScheduleModels); ok {
		r0 = rf(scheduleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ScheduleModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(scheduleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalItems provides a mock function with given fields:
func (_m *ScheduleRepositoryInterface) GetTotalItems() (int64, error) {
	ret := _m.Called()

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSchedule provides a mock function with given fields: scheduleID, updatedSchedule
func (_m *ScheduleRepositoryInterface) UpdateSchedule(scheduleID uint64, updatedSchedule *entities.ScheduleModels) error {
	ret := _m.Called(scheduleID, updatedSchedule)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, *entities.ScheduleModels) error); ok {
		r0 = rf(scheduleID, updatedSchedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewScheduleRepositoryInterface creates a new instance of ScheduleRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleRepositoryInterface {
	mock := &ScheduleRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
